/*
 * Copyright (c) CERN 2017
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-go.
// source: internal.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal.proto

It has these top-level messages:
	Transfer
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transfer struct {
	UserCN       string `protobuf:"bytes,1,opt,name=UserCN" json:"UserCN,omitempty"`
	Token        string `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Filepath     string `protobuf:"bytes,4,opt,name=Filepath" json:"Filepath,omitempty"`
	SubmitTime   int64  `protobuf:"varint,5,opt,name=SubmitTime" json:"SubmitTime,omitempty"`
	Origin       string `protobuf:"bytes,6,opt,name=Origin" json:"Origin,omitempty"`
	ListenerAddr string `protobuf:"bytes,7,opt,name=ListenerAddr" json:"ListenerAddr,omitempty"`
	Destination  string `protobuf:"bytes,8,opt,name=Destination" json:"Destination,omitempty"`
}

func (m *Transfer) Reset()                    { *m = Transfer{} }
func (m *Transfer) String() string            { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()               {}
func (*Transfer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transfer) GetUserCN() string {
	if m != nil {
		return m.UserCN
	}
	return ""
}

func (m *Transfer) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Transfer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Transfer) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *Transfer) GetSubmitTime() int64 {
	if m != nil {
		return m.SubmitTime
	}
	return 0
}

func (m *Transfer) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Transfer) GetListenerAddr() string {
	if m != nil {
		return m.ListenerAddr
	}
	return ""
}

func (m *Transfer) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*Transfer)(nil), "internal.Transfer")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x71, 0xe2, 0xee, 0xd6, 0x38, 0x8a, 0x87, 0x41, 0x64, 0xf0, 0x20, 0x65, 0x4f, 0x7b,
	0xf2, 0xe2, 0x13, 0x88, 0xe2, 0x49, 0x56, 0xa8, 0xf5, 0x01, 0x52, 0x3a, 0xea, 0x60, 0x3b, 0x29,
	0x93, 0xf8, 0xca, 0x3e, 0x87, 0x98, 0xaa, 0xd4, 0x5b, 0xfe, 0xbf, 0x04, 0x3e, 0x02, 0xa7, 0xa2,
	0x99, 0x4d, 0xc3, 0x70, 0x35, 0x59, 0xcc, 0x11, 0xfd, 0x6f, 0x6f, 0x3f, 0x1d, 0xf8, 0xd6, 0x82,
	0xa6, 0x17, 0x36, 0x3c, 0x87, 0xea, 0x39, 0xb1, 0xdd, 0xee, 0xc9, 0xd5, 0x6e, 0x77, 0xd4, 0xfc,
	0x14, 0x9e, 0xc1, 0xa6, 0x8d, 0xef, 0xac, 0x74, 0x50, 0x78, 0x0e, 0x44, 0x58, 0xef, 0xc3, 0xc8,
	0xb4, 0x2a, 0x58, 0xce, 0x78, 0x01, 0xfe, 0x5e, 0x06, 0x9e, 0x42, 0x7e, 0xa3, 0x75, 0xf1, 0xbf,
	0xc6, 0x4b, 0x80, 0xa7, 0x8f, 0x6e, 0x94, 0xdc, 0xca, 0xc8, 0xb4, 0xa9, 0xdd, 0x6e, 0xd5, 0x2c,
	0xe4, 0x7b, 0xfd, 0xd1, 0xe4, 0x55, 0x94, 0xaa, 0x79, 0x7d, 0x2e, 0xdc, 0xc2, 0xc9, 0x83, 0xa4,
	0xcc, 0xca, 0x76, 0xd3, 0xf7, 0x46, 0x87, 0xe5, 0xf6, 0x9f, 0x61, 0x0d, 0xc7, 0x77, 0x9c, 0xb2,
	0x68, 0xc8, 0x12, 0x95, 0x7c, 0x79, 0xb2, 0xa4, 0xae, 0x2a, 0x3f, 0xbf, 0xfe, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0x55, 0x91, 0x18, 0x0b, 0x01, 0x00, 0x00,
}
