#!/bin/bash
#
# chkconfig: - 93 17
# description: The lmt daemon
# processname: lmt

# Source function library
source /etc/rc.d/init.d/functions

instance=lmt

lmt=/usr/sbin/lmt
lmtconfig=/etc/lmt/config.yml
pidfile=/var/run/${instance}.pid
port=80

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

start() {
  if [ ! -f $lmtconfig ]; then
    echo "Error starting $instance: $lmtconfig not found!"
    return 3
  fi
  echo -n $"Starting $instance: "
  daemonize  -p ${pidfile} $lmt -conf $lmtconfig -port $port $OPTIONS
  RETVAL=$?
  echo
  if [ $RETVAL = 0 ]; then
    pid=$(ps aux | grep "$lmt" | grep -v grep | awk '{print $2}')
    if [ ! -z $pid ]; then
      echo $pid > $pidfile
    else
      echo "Error: could not retrieve lmt pid"
      RETVAL=3
    fi
  fi 
  return $RETVAL
}

stop() {
  echo -n $"Stopping $instance: "
  killproc -p ${pidfile} -d ${STOP_TIMEOUT} $lmt
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && rm -f ${pidfile}
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status -p ${pidfile} $lmt
    RETVAL=$?
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $lmt >&/dev/null; then
      stop
      start
    fi
    ;;
  *)
  echo "Usage: $instance {start|stop|restart|status}"
  RETVAL=2
  ;;
esac

exit $RETVAL
