#!/bin/bash
#
# @STARTUP_SCRIPT@            Startup script for the @STARTUP_SCRIPT@ server
#
# chkconfig: - 93 17
# description: The lmt daemon
# processname: lmt

# Source function library
source /etc/rc.d/init.d/functions


# Start httpd in the C locale by default.
LMT_LANG=${DOME_LANG-"C"}
LMT_USER=fts3
LMT_GROUP=fts3

instance="@STARTUP_SCRIPT@"

lmt=/usr/sbin/lmt
lmtconfig=/etc/lmt/config.yml
pidfile=/var/run/${instance}.pid

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

start() {
  if [ ! -f $lmtconfig ]; then
    echo "Error starting $instance: $lmtconfig not found!"
    return 3
  fi
  echo -n $"Starting $instance: "
  LANG=$LMT_LANG daemon --user=${LMT_USER} --pidfile=${pidfile} $lmt $lmtconfig $OPTIONS
  RETVAL=$?
  echo
  if [ $RETVAL = 0 ]; then
    pid=$(ps aux | grep "$lmt $lmtconfig" | grep -v grep | awk '{print $2}')
    if [ ! -z $pid ]; then
      echo $pid > $pidfile
    else
      echo "Error: could not retrieve lmt pid"
      RETVAL=3
    fi
  fi 
  return $RETVAL
}

stop() {
  echo -n $"Stopping $instance: "
  killproc -p ${pidfile} -d ${STOP_TIMEOUT} $lmt
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && rm -f ${pidfile}
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status -p ${pidfile} $lmt
    RETVAL=$?
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $lmt >&/dev/null; then
      stop
      start
    fi
    ;;
  *)
  echo "Usage: $instance {start|stop|restart|status}"
  RETVAL=2
  ;;
esac

exit $RETVAL
